Repository team-eeats/eeats-admin-fe, pull requests merged in 2024-10, with the labels that each got.

#7 ✨ :: login page 만들기
  src/Pages/loginPage/index.tsx
  src/Pages/loginPage/style.ts
  src/router.tsx
Labels: 퍼블리싱

#4 (#1) 사이드 바 퍼블리싱 및 레이아웃 추가
  src/Components/Layout.tsx
  src/Components/SideBar/index.tsx
  src/Components/SideBar/style.ts
  src/assets/img/SVG/Alert.svg
  src/assets/img/SVG/Logo.svg
  src/assets/img/SVG/Logout.svg
  src/assets/img/SVG/Page.svg
  src/assets/img/SVG/Vote.svg
  src/assets/img/SVG/WhiteAlert.svg
  src/assets/img/SVG/WhitePage.svg
  src/assets/img/SVG/WhiteVote.svg
  src/assets/img/SVG/index.ts
  src/router.tsx
Labels: 퍼블리싱

#13 건의 페이지 퍼블리싱
  src/Components/ModifyDeleteModal/index.tsx
  src/Components/UserSuggestBox/index.tsx
  src/Components/UserSuggestBox/style.ts
  src/Pages/suggestPage/hide.tsx
  src/Pages/suggestPage/index.tsx
  src/Pages/suggestPage/style.ts
  src/router.tsx
  yarn.lock
Labels: 퍼블리싱

#17 🎨 :: 자잘수정
  index.html
  src/router.tsx
Labels: 리팩토링, 퍼블리싱

#18 ✨ :: vote Page 퍼블리싱
  src/Components/VoteType/style.ts
  src/Pages/votePage/index.tsx
  src/Pages/votePage/style.ts
  src/router.tsx
Labels: 퍼블리싱

#20 (#10) 공지사항 퍼블리싱
  src/Components/ModifyDeleteModal/index.tsx
  src/Components/Notice/index.tsx
  src/Components/Notice/style.ts
  src/Pages/Notice/AddNotice.tsx
  src/Pages/Notice/ModifyNotice.tsx
  src/Pages/Notice/index.tsx
  src/Pages/Notice/style.ts
  src/router.tsx
  src/store/useInputStore.ts
Labels: 퍼블리싱

#21 AdminCalendar 퍼블리싱
  src/Components/adminCalendar/index.tsx
  src/Components/adminCalendar/style.ts
Labels: 퍼블리싱

#25 24 뭔가 잘못된거 해결하기
  src/Components/voteModal/index.tsx
  src/Components/voteModal/style.ts
  src/Pages/makingVotePage/index.tsx
  src/Pages/makingVotePage/style.ts
  src/assets/img/SVG/Ximg.svg
  src/assets/img/SVG/addButton.svg
  src/assets/img/SVG/imgfile.svg
  src/router.tsx
Labels: 기능 개발, 퍼블리싱
